float4x4 WorldViewProjectionMatrix : WorldViewProjection;

struct v2f 
{
    float4 Position:    POSITION;
    float4 Color:       COLOR;
};

v2f VS(float3 Position: POSITION, float4 color:COLOR) 
{
    v2f output;
    output.Position = mul(WorldViewProjectionMatrix, float4(Position.xyz,1));
    output.Color = color;
    return output;
}

float4 FS(v2f input) : COLOR 
{
    return input.Color;
}

